language: go
go:
- 1.13
env:
  - GO111MODULE=on
addons:
  apt:
    packages:
      - python-pygments
install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo_0.48_Linux-64bit.deb
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get golang.org/x/lint/golint
script:
  - go fmt ./...
  - golint ./...
  - go vet ./...
  - go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=${COVERALLS_TOKEN}
after_success:
  - cd docs && hugo && mv docs/* .
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: docs
